name: Python Template CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - name: Install Pipenv
        run: pip install pipenv

      - name: Install virtual env
        run: pipenv install --dev

      - name: Check Types
        run: pipenv run mypy
        
      - name: Run Tests
        run: pipenv run pytest
          