name: Python Template CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Pipenv
        run: pip install pipenv

      - name: Install virtual env
        run: pipenv install --dev

      - name: Check Types
        run: pipenv run mypy
        
      - name: Run Tests
        run: pipenv run pytest
          